name = "griggy"
author = "bont"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "667aa9b46be0be6c5da509e55c96c01a44de437b380ec03a3853db3bd6b79d86"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
