name = "griggy"
author = "bont"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19c5f9cc4a5c58d220c46ddeb8882a5b929cb45a5bfb18d213d31742b36c6eec"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
