name = "griggy"
author = "bont"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "548313c3eabe8e1a40a497f6702a6a4310f13342c2395a36451ae540c17dee34"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
